; PlatformIO Project Configuration File for Smart Medical ICU Safety System
; Target: STM32 Black Pill (STM32F401CCU6 / STM32F411CEU6)

[platformio]
default_envs = blackpill_f401cc

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = stlink
monitor_speed = 115200

build_flags =
    -Iinclude
    -O2
    -Wall
    -Wextra
    -DARDUINO_BLACKPILL_F401CC

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5

; Native Host Simulation & Test Environment
[env:native]
platform = native
build_flags =
    -Iinclude
    -Itests
    -lm
